# Generated by Django 3.0.6 on 2020-05-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_img',
            name='url',
        ),
        migrations.AddField(
            model_name='blog_img',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='blog_img/'),
        ),
    ]
