# Generated by Django 3.0.6 on 2020-05-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200525_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_area', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('moderated', models.BooleanField(default=True)),
            ],
        ),
    ]
