# Generated by Django 3.0.6 on 2020-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200528_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='author_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='course_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='teacher_id',
            field=models.IntegerField(blank=True),
        ),
    ]
