# Generated by Django 3.0.6 on 2020-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200528_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='student_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
