# Generated by Django 3.0.6 on 2020-05-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_testimonials_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
