# Generated by Django 3.0.6 on 2020-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('free_access', models.BooleanField(default=False)),
                ('paid_access', models.BooleanField(default=False)),
                ('lesson_access', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(blank=True, upload_to='students_photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('photo_main', models.ImageField(blank=True, upload_to='teachers_photos/%Y/%m/%d')),
                ('course', models.CharField(max_length=200)),
            ],
        ),
    ]
