# Generated by Django 3.0.6 on 2020-05-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='google',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='twitter',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='google',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
