# Generated by Django 3.0.6 on 2020-05-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200520_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='students_photos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='teachers_photos/'),
        ),
    ]
