# Generated by Django 3.0.6 on 2020-05-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200520_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='username',
        ),
    ]
