# Generated by Django 3.0.6 on 2020-05-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200520_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
