# Generated by Django 3.0.6 on 2020-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(null=True, upload_to='video_course<django.db.models.fields.CharField>', verbose_name=''),
        ),
    ]
