# Generated by Django 3.0.6 on 2020-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200518_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(null=True, upload_to='video_course', verbose_name=''),
        ),
    ]
