# Generated by Django 3.0.6 on 2020-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='courses_img/'),
        ),
    ]
