# Generated by Django 3.0.6 on 2020-05-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='ready_for_check',
            field=models.BooleanField(default=False),
        ),
    ]
