# Generated by Django 3.0.6 on 2020-05-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200525_2028'),
        ('courses', '0007_auto_20200528_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
            preserve_default=False,
        ),
    ]
