# Generated by Django 3.0.6 on 2020-05-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200525_2028'),
        ('courses', '0008_task_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Teacher'),
            preserve_default=False,
        ),
    ]
